require: sudo

env:
  - RAILS_ENV=test

services:
  - docker

before_install:
  - cp .env.example .env
  - docker-compose build client
  - docker-compose build api

script:
  - docker-compose run --rm client npm run ci-test
  - docker-compose run --rm api rake db:create db:migrate
  - docker-compose run --rm api rubocop
  - docker-compose run --rm api rspec

after_success:
  - docker build -t vladimirkuchinskiy/task-tracker-client ./todo-react
  - docker build -t vladimirkuchinskiy/task-tracker-server ./todo-rails
  - docker build -t vladimirkuchinskiy/task-tracker-nginx ./nginx
  # Login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push vladimirkuchinskiy/task-tracker-client
  - docker push vladimirkuchinskiy/task-tracker-server
  - docker push vladimirkuchinskiy/task-tracker-nginx

deploy:
  provider: elasticbeanstalk
  region: eu-central-1
  app: task-tracker
  env: TaskTracker-env
  bucket_name: elasticbeanstalk-eu-central-1-833679727268
  bucket_path: task-tracker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY

