version: "3"

services:
  api:
    build:
      dockerfile: "Dockerfile.dev"
      context: ./todo-rails
    env_file: ./todo-rails/.env
    volumes:
      - ./todo-rails:/app
    depends_on:
      - db
      - redis
    stdin_open: true
    tty: true
  nginx:
    restart: always
    build:
      dockerfile: "Dockerfile.dev"
      context: ./nginx
    ports:
      - "3050:80"
  sidekiq:
    build:
      dockerfile: "Dockerfile.dev"
      context: ./todo-rails
    env_file: ./todo-rails/.env
    command: bundle exec sidekiq -C config/sidekiq.yml
  db:
    image: postgres:10.3-alpine
    volumes:
      - ./db-data:/var/lib/postgresql/db-data
  redis:
    image: redis:5.0.5-alpine
  # mailcatcher:
  #   image: yappabe/mailcatcher
  #   ports:
  #     - 1025:1025
  #     - 1080:1080
  client:
    build:
      dockerfile: "Dockerfile.dev"
      context: ./todo-react
    volumes:
      - /app/node_modules
      - ./todo-react:/app
