AllCops:
  Exclude:
    - "bin/*"
    - "node_modules/**/**"
    - "db/schema.rb"
    - "db/migrate/*.rb"
Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 120
Metrics/BlockLength:
  Exclude:
    - "Rakefile"
    - "**/*.rake"
    - "spec/**/*.rb"
    - "config/environments/development.rb"
    - "config/environments/production.rb"
# RSpec/NestedGroups:
#   Max: 6
