default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: <%= ENV["PGUSER"] %>
  password: <%= ENV["PGPASSWORD"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test

production:
  <<: *default
  database: app_production
  host: <%= ENV["POSTGRES_HOST"] %>
  password: <%= ENV['PGPASSWORD'] %>
