// Boards
export const GET_BOARDS_START = 'GET_BOARDS_START';
export const GET_BOARDS_SUCCESS = 'GET_BOARDS_SUCCESS';
export const CREATE_BOARD = 'CREATE_BOARD';
export const UPDATE_BOARD = 'UPDATE_BOARD';
export const DELETE_BOARD_START = 'DELETE_BOARD_START';
export const DELETE_BOARD_SUCCESS = 'DELETE_BOARD_SUCCESS';

// Board
export const GET_BOARD_START = 'GET_BOARD_START';
export const GET_BOARD_SUCCESS = 'GET_BOARD_SUCCESS';

// List
export const CREATE_LIST = 'CREATE_LIST';
export const UPDATE_LIST = 'UPDATE_LIST';
export const DELETE_LIST = 'DELETE_LIST';
export const MOVE_LIST = 'MOVE_LIST';

// Card
export const GET_CARD = 'GET_CARD';
export const CREATE_CARD = 'CREATE_CARD';
export const UPDATE_CARD = 'UPDATE_CARD';
export const DELETE_CARD = 'DELETE_CARD';
export const MOVE_CARD = 'MOVE_CARD';
export const CREATE_ASSIGNMENT = 'CREATE_ASSIGNMENT';
export const DELETE_ASSIGNMENT = 'DELETE_ASSIGNMENT';

// Auth
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_SIGN_OUT = 'AUTH_SIGN_OUT';

// Teams
export const GET_TEAMS_START = 'GET_TEAMS_START';
export const GET_TEAMS_SUCCESS = 'GET_TEAMS_SUCCESS';
export const CREATE_TEAM = 'CREATE_TEAM';
export const UPDATE_TEAM = 'UPDATE_TEAM';

// Team
export const GET_TEAM_START = 'GET_TEAM_START';
export const GET_TEAM_SUCCESS = 'GET_TEAM_SUCCESS';
export const CREATE_BOARD_FOR_TEAM = 'CREATE_BOARD_FOR_TEAM';
export const SEARCH_USERS = 'SEARCH_USERS';
export const INVITE_USER = 'INVITE_USER';

// Invites
export const GET_INVITES_START = 'GET_INVITES_START';
export const GET_INVITES_SUCCESS = 'GET_INVITES_SUCCESS';
export const MAKE_INVITATION_RESPONSE = 'MAKE_INVITATION_RESPONSE';

// Profile -> Info
export const GET_PROFILE_START = 'GET_PROFILE_START';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';

// Profile -> Avatar
export const CHANGE_AVATAR = 'CHANGE_AVATAR';
export const CHANGE_IMAGE_FILE = 'CHANGE_IMAGE_FILE';
export const CHANGE_CROP_AND_PIXEL_CROP = 'CHANGE_CROP_AND_PIXEL_CROP';
export const CHANGE_IMAGE = 'CHANGE_IMAGE';

// Profile -> Membership
export const GET_SUBSCRIPTION_START = 'GET_SUBSCRIPTION_START';
export const GET_SUBSCRIPTION_SUCCESS = 'GET_SUBSCRIPTION_SUCCESS';
export const GET_CLIENT_TOKEN = 'GET_CLIENT_TOKEN';
export const SET_INSTANCE = 'SET_INSTANCE';
export const BUY_MEMBERSHIP_START = 'BUY_MEMBERSHIP_START';
export const BUY_MEMBERSHIP_LOADING_FINISH = 'BUY_MEMBERSHIP_LOADING_FINISH';
export const CANCEL_SUBSCRIPTION_START = 'CANCEL_SUBSCRIPTION_START';
export const CANCEL_SUBSCRIPTION_SUCCESS = 'CANCEL_SUBSCRIPTION_SUCCESS';
